[package]
name = "tank-hunter"
version = "0.1.0"
authors = ["Tom Wall <twall@millennialmedia.com>"]

[dependencies]
iron = "0.4.*"
rustc-serialize = "*"
router="0.4.0"
hyper="*"
crossbeam="*"
classifier = "0.0.3"
select = "0.3.0"
time = "0.1"
